"""complete comment table

Revision ID: b56195972093
Revises: a45615c6680a
Create Date: 2019-11-26 22:06:40.291250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56195972093'
down_revision = 'a45615c6680a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('has_reply', sa.Boolean(), nullable=True))
    op.add_column('comment', sa.Column('is_reply', sa.Boolean(), nullable=True))
    op.add_column('comment', sa.Column('reply', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'reply')
    op.drop_column('comment', 'is_reply')
    op.drop_column('comment', 'has_reply')
    # ### end Alembic commands ###
