"""complete comment table and fix bugs

Revision ID: fae378ed3772
Revises: b56195972093
Create Date: 2019-11-27 10:44:50.019151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae378ed3772'
down_revision = 'b56195972093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reply_to', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'reply_to')
    # ### end Alembic commands ###
